### ISSUE TITLE
`adapter` is not a function

### ISSUE THREAD

**Issue by d3rpp** [storyblok/storyblok-js#147]
I'm attempting to use the js client to access my stories, and I'm running into an issue with how y'all are using `axios` I think

Stacktrace (Paths partially removed for privacy reasons, `~` is the project root)
```stacktrace
TypeError: adapter is not a function
    at dispatchRequest (~/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (~/node_modules/axios/lib/core/Axios.js:109:15)
    at Axios. [as get] (~/node_modules/axios/lib/core/Axios.js:131:17)
    at Function.wrap2 [as get] (~/node_modules/axios/lib/helpers/bind.js:9:15)
    at h.throttledRequest (~/node_modules/@storyblok/js/dist/storyblok-js.mjs:641:24)
    at a2 (~/node_modules/@storyblok/js/dist/storyblok-js.mjs:340:19)
    at ~/node_modules/@storyblok/js/dist/storyblok-js.mjs:344:76
    at new Promise ()
    at h.l2 [as throttle] (~/node_modules/@storyblok/js/dist/storyblok-js.mjs:343:12)
    at ~/node_modules/@storyblok/js/dist/storyblok-js.mjs:628:29
```

Code causing this issue (Qwik city application):

```ts
export const onGet: RequestHandler<BlogPost> = async ({
	params,
	response,
	platform,
}) => {
	if (params.slug == '') return;

	if (storyblokApi == undefined) {
		storyblokApi = storyblokInit({
			accessToken: platform.STORYBLOK_KEY,
			use: [apiPlugin],
		}).storyblokApi;
	}

	if (!storyblokApi) {
		const re = response.error(500);
		re.message = 'STORYBLOK API UNINITIALISED';
		throw re;
	}
	
	const { data } = await storyblokApi.get(`cdn/stories/${params.slug}`, {
		version: 'published',
	});

	return data.story;
};
```

**Comment by d3rpp** [comment]
Just for the funny it's also in prod

https://48ff6415.d3rpp-dev-qwik.pages.dev/blog/holy-shit

good ol' cloudflare

**Comment by d3rpp** [comment]
I've archived the repo because i have no clue why it's not working

https://gitlab.com/d3rpp/d3rpp.dev-qwik

Feel free to yell at my code to take a guess as to the problem

**Comment by fgiuliani** [comment]
Closing issue as Storyblok JS SDK was updated and Axios is not used anymore
https://github.com/storyblok/storyblok-js/pull/173
